### ISSUE TITLE
Relation to CSS' element()

### ISSUE THREAD

**Issue by chrisguttandin** [screen-share/element-capture#1]
There is an `element()` function in CSS which does a similar thing. It's a still a draft but a prefixed version is already available in Firefox. Maybe it makes sense to use the same algorithm to render the captured element in isolation.

https://w3c.github.io/csswg-drafts/css-images-4/#element-notation

**Comment by eladalon1983** [comment]
Yes, @mfoltzgoogle has raised this internally. And I think @baylesj is currently looking into [stacking contexts](https://w3c.github.io/csswg-drafts/css2/#stacking-context).

**Comment by markafoltz** [comment]
@eladalon1983 This issue can be closed.

**Comment by bradisbell** [comment]
Link to the Chromium bug, for anyone else following:  https://issues.chromium.org/u/1/issues/40133523
