### ISSUE TITLE
Transparency in the output

### ISSUE THREAD

**Issue by eladalon1983** [screen-share/element-capture#16]
When capturing an entire tab, all pixels are completely opaque. But what when capturing an element? Some of its pixels could be partially or fully transparent.

If getDisplayMedia() outputs a transparency-capable format, there is no issue. This is the ideal case, and should be the long-term goal of any implementation. The rest of this issue deals with a fallback in the short- and medium-term.

The specification has several options for what it could mandate if gDM cannot return a transparency-capable format, including:
1. Remove the alpha-value of all pixels, making them opaque.
2. Blend transparent pixels with an arbitrary value (likely white, possibly black).
3. Blend transparent pixels with a value of the app's choosing.
4. Blend transparent pixels with the target element's own [background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color), with the alpha channel cleared out.
5. Blend transparent pixels with the body's own color.

I think the best would be:
* Long-term, all implementations should return a transparency-capable format (if the application requests it).
* Medium-term, we could consider option 3, though arguably it'd become throw-away work once an implementation supports a transparency-capable format.
* Short-term, it should be easy and mostly sufficient to specify option 1.

**Comment by khushalsagar** [comment]
> If getDisplayMedia() outputs a transparency-capable format, there is no issue.

What are the cases where this won't happen. If the format in which the video is being encoded is in control of the site, can we force them to use a format which supports transparency if the stream is for element capture?

**Comment by mfoltzgoogle** [comment]
In terms of implementation, what is happening right now in Chrome is No 2, as the element is rendered on a black background and the alpha channel is dropped from the blended result.  This can be observed by playing around with https://element-capture-body.glitch.me/ and adjusting the opacity of the inner divs.

**Comment by markafoltz** [comment]
Until there is a way for applications to dictate a pixel format, I don't think we can define behavior for different pixel format scenarios.  However, a note that browsers _may_ use a black background for rendering the element seems advisable so developers have some idea of what to expect.

**Comment by eladalon1983** [comment]
> a note that browsers _may_ use a black background for rendering the element seems advisable so developers have some idea of what to expect.

Is this significantly enough different from the existing following note?

> Note
>
> In some implementations, the underlying pixel format for the frame data will not be able to carry alpha channel information. > In this case, the implementation can blend the rendered frame with an infinite canvas of black (rgb(0,0,0)).

If there's more information you'd like to convey with the note - I am happy to take a look at a PR.

Maybe we could also consider expanding the comment to suggest that prudent developers would make sure to use a target-element with a known, included background, unless they have a good reason to skip that. Wdyt?

**Comment by markafoltz** [comment]
Yes, the note added to #46 is what I was thinking.  I don't think further clarification is needed on this.
