### ISSUE TITLE
Clarification in valid restriction targets

### ISSUE THREAD

**Issue by beaufortfrancois** [screen-share/element-capture#19]
In the [note](https://screen-share.github.io/element-capture/#valid-restriction-targets) below, it is not clear to me where the spec says the track is associated with tab-capture. Is this "The top-level browsing context of the display surface that is the source of T, is E's shadow-including root"?

> Informally, this means that T is an active video track associated with tab-capture, and E is an Element [connected](https://dom.spec.whatwg.org/#connected) to the DOM in the captured tab.

**Comment by eladalon1983** [comment]
>  Is this "The top-level browsing context of the display surface that is the source of T, is E's shadow-including root"?

That's the part that intends to form that connection, yes.

**Comment by beaufortfrancois** [comment]
I wonder if we could **add** something like `T.settings.displaySurface = "browser"` in https://screen-share.github.io/element-capture/#restrictable-tracks to make it clearer.

**Comment by eladalon1983** [comment]
I've created #20 for this, could you PTAL? (I personally dislike my own conditionally-phrased clarification around `getSettings()`, but I don't see a simple way to avoid it. Possibly the entire definition could be rephrased as an algorithm, but that seems like overkill to me atm.)
