### ISSUE TITLE
Improve specification of what is captured/excluded

### ISSUE THREAD

**Issue by eladalon1983** [screen-share/element-capture#2]
As of the time of writing, the spec is missing a "proper" definition of what is captured/excluded, resorting instead to a hand-wavy definition. (I believe issue #1 alludes to this.)

**Comment by mfoltzgoogle** [comment]
There is some prior art in the [CSS draft for `element()`](https://drafts.csswg.org/css-images-4/#element-notation), however, the process is different.   CSS is producing an image which can be inserted back into the document, while we are producing a video frame which is going to go through various transformations before being delivered to the media stream consumer.

I can try to come up with a PR that covers our simplified use case and matches our implementation experience.

**Comment by markafoltz** [comment]
@eladalon1983 This issue can be closed.
