### ISSUE TITLE
CropTarget, RestrictionTarget, or something else?

### ISSUE THREAD

**Issue by eladalon1983** [screen-share/element-capture#21]
As of the time of writing, Element Capture reuses [CropTarget](https://w3c.github.io/mediacapture-region/#dom-croptarget).
```webidl
[Exposed = Window]
partial interface BrowserCaptureMediaStreamTrack {
  Promise<undefined> restrictTo(CropTarget? cropTarget);
};
```

Pros:
* Simplicity: Avoids introducing additional types unnecessarily.
* Ergonomics: Keeps `cropTo()` and `restrictTo()` similar and allow documents to `postMessage()` a single token that could serve either.

Cons:
* Naming: The name "CropTarget" is misleading in the context of `restrictTo()`.
* Security: Some concerns; see below.

<p align="center">
  <img width="608" alt="image" src="https://github.com/screen-share/element-capture/assets/22117736/685afaff-32c3-4027-8bf1-56a28508bc78">
</p>

Consider a document from `EMBEDDED` that previously posted a `CropTarget` to a **cross-origin document** `EMBEDDER`. The team at `EMBEDDED` might have reasoned that no special permissions were being granted by posting this token, and this was correct at the time when only cropTo() could use CropTarget. But by reusing CropTarget for `restrictTo()`,  the posting of the CropTarget object now implicitly includes permission to remove occlusions from a capture, which might not have been intended by `EMBEDDED`.

**Comment by eladalon1983** [comment]
I've vacillated between the opinion of using a new bespoke token, and that of reusing the existing token, quite a few times. Presently I prefer using a new token. As this particular issue was not explicitly discussed, I'll go ahead and change the spec, and raise the topic for discussion during the upcoming SCCG meeting in TPAC 2023. Opinions welcome both here and there.

(FWIW, Chrome's implementation of both tokens will likely be shared under the hood.)

CC @baylesj @mfoltzgoogle @alvestrand

**Comment by mfoltzgoogle** [comment]
The current spec adds a new token type, `RestrictionTarget`.  I believe this can be closed out.
