### ISSUE TITLE
Detect whether an element is eligible for capture

### ISSUE THREAD

**Issue by mfoltzgoogle** [screen-share/element-capture#31]
In Chrome's implementation, elements must meet certain criteria to be eligible for capture; this is also outlined in the spec:

 https://screen-share.github.io/element-capture/#elements-eligible-for-restriction

Developers may find it helpful to know whether an element is currently eligible for element capture.  This could help with debugging site layout and style that might interfere with capture, or with offering a UI that gives users a choice of which element should be captured (so that non-eligible elements aren't offered).

**Comment by mfoltzgoogle** [comment]
With PR #34, we no longer require elements to be eligible for capture to call restrictTo().  Therefore developers can indirectly determine whether the element is eligible by seeing if frames are being produced for a given target (assuming that other conditions are met).

**Comment by eladalon1983** [comment]
In the future, it might be useful to expose a MuteReason when this happens ([link](https://github.com/w3c/mediacapture-extensions/issues/39#issuecomment-1824690716)). For now, I think the state of the art is satisfactory - I expect most applications can structure themselves to avoid making the target-element ineligible for capture. Failure to produce frames will likely be caught in testing.

**Comment by mfoltzgoogle** [comment]
@eladalon1983  can this be closed out with PR #34?
