### ISSUE TITLE
Is the backdrop root condition redundant with the stacking context condition?

### ISSUE THREAD

**Issue by eladalon1983** [screen-share/element-capture#39]
Is it even possible to have an Element which does not form a [backdrop root](https://drafts.fxtf.org/filter-effects-2/#backdrop-root), but which does form its own *stacking context*? If not, we can drop the mention of backdrop root from the spec.

**Comment by mfoltzgoogle** [comment]
My understanding is that this is possible.  For example the following is sufficient to create a stacking context:

```
#target {
  isolation: isolate;     /* Forms a stacking context. */
}
```

But `#target` may not meet any of the conditions for a backdrop root because it is completely opaque, doesn't have a filter, doesn't have a clip mask, etc. etc.

**Comment by mfoltzgoogle** [comment]
Can this be closed out in light of my previous reply?
