### ISSUE TITLE
Non-realtime recording of an element

### ISSUE THREAD

**Issue by Technickel-Dev** [screen-share/element-capture#41]
Is there a way to get a faster than realtime capture of an element? Much like the issue set out in [Ability to record non-realtime / frame-by-frame](https://github.com/w3c/mediacapture-record/issues/213) for the MediaStream Recording API, taking the track from element capture and piping it into a MediaRecorder gives a realtime video (ie. it realistically takes around 10 seconds of recording an element to get around 10 seconds of video output)

The working [solution](https://github.com/w3c/mediacapture-record/issues/213#issuecomment-1430325280) for that thread shows manual manipulation of the frame capture of the canvas element and muxing the frames back into the final video. In the element capture case, we don't have a handy `track.requestFrame()` to manipulate as that only exists on the [CanvasCaptureMediaStreamTrack](https://developer.mozilla.org/en-US/docs/Web/API/CanvasCaptureMediaStreamTrack/requestFrame) and avoiding working exclusively in the world of canvas is ideal.

### Use Case

I'm using element capture as a way to make user generated videos based on the current layout of the element. When the element being captured is in the state the user is happy with they COULD wait the entire duration of the recording but I believe there should be a way to go faster.

### Attempts

I've played around with doing a similar setup to the aforementioned [solution](https://github.com/w3c/mediacapture-record/issues/213#issuecomment-1430325280) and using [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) to force an animation to play in faster than realtime in a theoretically similar fashion but have had no direct luck.

Another train of thought I had was using a [single frame](https://github.com/screen-share/element-capture/issues/5) and duplicating it out into a video but that would ultimately not support different animations that would enhance the element that was being captured.

Looking forward to seeing what others come up with or if this sort of functionality could be capable!

**Comment by eladalon1983** [comment]
> Is there a way to get a faster than realtime capture of an element?

That's not currently in scope for the API. Element Capture will, for the time being, capture at the frame rate which the original capture had. (But how about you call `getDisplayMedia()` with a higher frame rate and speed that up in post?)

**Comment by Technickel-Dev** [comment]
Very fair! Keep up the great work, loving the API and I appreciate the suggestion!
