### ISSUE TITLE
Web platform tests?

### ISSUE THREAD

**Issue by markafoltz** [screen-share/element-capture#53]
I didn't see any Web platform tests for element capture under https://github.com/web-platform-tests/wpt/tree/master/screen-capture.  Presumably tests would need some consistent way to fake the dialog for tab self-capture, but otherwise it should be possible to write some?

**Comment by eladalon1983** [comment]
I remember Jordan added at least [these tests](https://chromium-review.googlesource.com/c/chromium/src/+/5404107). I have a vague recollection of more; I could check when back from vacation next week.

**Comment by eladalon1983** [comment]
I believe these are sufficient for now, so closing; please let me know otherwise.
