### ISSUE TITLE
Should explicitly specify what to do with the mouse cursor

### ISSUE THREAD

**Issue by JonnyBurger** [screen-share/element-capture#6]
The spec does not touch on whether the mouse cursor should be captured. For the editor use-case you would want to be able to hide the mouse cursor.

Since currently in screen sharing in Chrome, the cursor is visible, it would be cool if the spec is clearly defining a behavior.

**Comment by eladalon1983** [comment]
That seems to already be covered by [CursorCaptureConstraint](https://www.w3.org/TR/screen-capture/#cursorcaptureconstraint), doesn't it?

**Comment by JonnyBurger** [comment]
It does! Great, this answers my question 👍
