### ISSUE TITLE
Append `navigator.mediaDevices.getDisplayMedia()` to allow sharing of the same tab

### ISSUE THREAD

**Issue by JonnyBurger** [screen-share/element-capture#7]
I notice the following: Currently when calling `navigator.mediaDevices.getDisplayMedia()`, you cannot select the tab that has initialized the screenshare - you can only select other tabs!

For supporting the new use cases, you would want to record the same tab. Even greater applications could be created if developers can specify that the current tab should be recorded and disable the other options.

<img width="1076" alt="image" src="https://github.com/screen-share/element-capture/assets/1629785/69233652-908f-407d-989e-50672d4914a8">

**Comment by eladalon1983** [comment]
Hi @JonnyBurger.
1. This is not a spec issue, it's a Chromium issue.
2. That's not actually an issue - see the write-up [here](https://developer.chrome.com/docs/web-platform/screen-sharing-controls/#selfBrowserSurface). (TL;DR - use `selfBrowserSurface: "include"`.)
